export { default as Hero } from './Hero';
export { default as Features } from './Features';
export { default as CTA } from './CTA';
export { default as Pricing } from './Pricing';
export { default as PricingPreview } from './PricingPreview';
export { default as Location } from './Location';
export { default as Newsletter } from './Newsletter';
export { default as SocialFeed } from './SocialFeed';
export { default as Testimonials } from './Testimonials';
